# Generated by Django 5.1.3 on 2024-11-21 02:54

import cpf_field.models
import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funcao', models.CharField(choices=[('P', 'Prestador'), ('C', 'Cliente')], max_length=100)),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='cpf')),
                ('endereco', models.CharField(max_length=150)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('cep', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='O CEP deve estar no formato 12345-678.', regex='^\\d{5}-\\d{3}$')])),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
